[package]
name = "hexarc-tracker"
version = "0.1.0"
edition = "2021"
authors = ["Max Koverdyaev <shadeglare@gmail.com>"]

[dependencies]
actix-web = "4.1.0"
mongodb = "2.3.0"
serde = { version = "1.0.140", features = ["derive"] }

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[profile.dev]
split-debuginfo = "unpacked"
