[package]
name = "hexarc-badger"
version = "0.1.0"
edition = "2021"
authors = ["Max Koverdyaev <shadeglare@gmail.com>"]

[dependencies]
actix-web = "4.1.0"
rand = "0.8.5"
serde = { version = "1.0.140", features = ["derive"] }
